services:
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    networks:
      - postcoil-net
    ports:
      - "9308:9308"
    command:
      - "--kafka.server=kafka-1:9092"
      - "--kafka.server=kafka-2:9092"
      - "--kafka.server=kafka-3:9092"

  prometheus:
    image: prom/prometheus:latest
    networks:
      - postcoil-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - kafka-exporter

  grafana:
    image: grafana/grafana:latest
    networks:
      - postcoil-net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: