INSERT INTO ROLL_UNIT (roll_unit_name, criteria_value, criteria_type)
VALUES ('A', 0.6, 'LESS_THAN'),
       ('B', 0.6, 'GREATER_THAN');

INSERT INTO extraction_criteria_mapper (process_code, extraction_group) VALUES ('1PCM', '1PCM추출기준');
INSERT INTO extraction_criteria_mapper (process_code, extraction_group) VALUES ('2PCM', '2PCM추출기준');
INSERT INTO extraction_criteria_mapper (process_code, extraction_group) VALUES ('1CAL', '1CAL추출기준');
INSERT INTO extraction_criteria_mapper (process_code, extraction_group) VALUES ('2CAL', '2CAL추출기준');
INSERT INTO extraction_criteria_mapper (process_code, extraction_group) VALUES ('1EGL', '1EGL추출기준');
INSERT INTO extraction_criteria_mapper (process_code, extraction_group) VALUES ('2EGL', '2EGL추출기준');
INSERT INTO extraction_criteria_mapper (process_code, extraction_group) VALUES ('1CGL', '1CGL추출기준');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (1, 'factory_code', 'L');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (1, 'material_status', '2');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (1, 'progress', 'D');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (1, 'curr_proc', '1PCM');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (2, 'factory_code', 'L');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (2, 'material_status', '2');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (2, 'progress', 'D');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (2, 'curr_proc', '2PCM');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (3, 'factory_code', 'L');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (3, 'material_status', '2');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (3, 'progress', 'D');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (3, 'curr_proc', '1CAL');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (4, 'factory_code', 'L');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (4, 'material_status', '2');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (4, 'progress', 'D');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (4, 'curr_proc', '2CAL');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (5, 'factory_code', 'L');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (5, 'material_status', '2');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (5, 'progress', 'D');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (5, 'curr_proc', '1EGL');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (6, 'factory_code', 'L');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (6, 'material_status', '2');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (6, 'progress', 'D');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (6, 'curr_proc', '2EGL');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (7, 'factory_code', 'L');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (7, 'material_status', '2');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (7, 'progress', 'D');
INSERT INTO extraction_criteria (mapper_id, column_name, column_value) VALUES (7, 'curr_proc', '1CGL');


INSERT INTO error_criteria_mapper (process_code, error_group) VALUES ('1PCM', '1PCM에러기준');
SET @mapper_id = (SELECT MAX(id) FROM error_criteria_mapper WHERE process_code = '1PCM' AND error_group = '1PCM에러기준');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_thickness', '1.2');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_thickness', '5.2');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_width', '500');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_width', '1385');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '관리재', 'coil_type_code', 'ATOS');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'factory_code', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'order_no', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'rem_proc', NULL);
INSERT INTO error_criteria_mapper (process_code, error_group) VALUES ('2PCM', '2PCM에러기준');
SET @mapper_id = (SELECT MAX(id) FROM error_criteria_mapper WHERE process_code = '2PCM' AND error_group = '2PCM에러기준');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_thickness', '2.0');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_thickness', '5.0');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_width', '620');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_width', '1685');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '관리재', 'coil_type_code', 'ATOS');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'factory_code', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'order_no', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'rem_proc', NULL);
INSERT INTO error_criteria_mapper (process_code, error_group) VALUES ('1CAL', '1CAL에러기준');
SET @mapper_id = (SELECT MAX(id) FROM error_criteria_mapper WHERE process_code = '1CAL' AND error_group = '1CAL에러기준');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_thickness', '0.14');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_thickness', '1.7');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_width', '495');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_width', '1278');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '관리재', 'coil_type_code', 'ATOS');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'factory_code', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'order_no', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'rem_proc', NULL);
INSERT INTO error_criteria_mapper (process_code, error_group) VALUES ('2CAL', '2CAL에러기준');
SET @mapper_id = (SELECT MAX(id) FROM error_criteria_mapper WHERE process_code = '2CAL' AND error_group = '2CAL에러기준');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_thickness', '0.38');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_thickness', '2.1');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_width', '613');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_width', '1660');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '관리재', 'coil_type_code', 'ATOS');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'factory_code', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'order_no', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'rem_proc', NULL);
INSERT INTO error_criteria_mapper (process_code, error_group) VALUES ('1EGL', '1EGL에러기준');
SET @mapper_id = (SELECT MAX(id) FROM error_criteria_mapper WHERE process_code = '1EGL' AND error_group = '1EGL에러기준');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_thickness', '0.4');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_thickness', '2.3');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_width', '800');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_width', '1650');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '관리재', 'coil_type_code', 'ATOS');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'factory_code', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'order_no', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'rem_proc', NULL);
INSERT INTO error_criteria_mapper (process_code, error_group) VALUES ('2EGL', '2EGL에러기준');
SET @mapper_id = (SELECT MAX(id) FROM error_criteria_mapper WHERE process_code = '2EGL' AND error_group = '2EGL에러기준');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_thickness', '0.4');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_thickness', '2');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_width', '800');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_width', '1650');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '관리재', 'coil_type_code', 'ATOS');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'factory_code', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'order_no', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'rem_proc', NULL);
INSERT INTO error_criteria_mapper (process_code, error_group) VALUES ('1CGL', '1CGL에러기준');
SET @mapper_id = (SELECT MAX(id) FROM error_criteria_mapper WHERE process_code = '1CGL' AND error_group = '1CGL에러기준');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_thickness', '0.35');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_thickness', '2.3');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'min_width', '800');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '설비이상에러재', 'max_width', '1860');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '관리재', 'coil_type_code', 'ATOS');
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'factory_code', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'order_no', NULL);
INSERT INTO error_criteria (mapper_id, error_type, column_name, column_value) VALUES (@mapper_id, '정보이상재', 'rem_proc', NULL);
