spring.application.name=gateway

---
server:
  port: 8080

---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: operation
          uri: http://localhost:8081/
          predicates:
            - Path=/api/operation/**
          filters:
            - name: OperationFilter
              args:
                baseMessage: Spring Cloud Gateway OperationFilter
                preLogger: true
                postLogger: true
        - id: control
          uri: http://localhost:8083/
          predicates:
            - Path=/api/control/**
          filters:
            - name: ControlFilter
              args:
                baseMessage: Spring Cloud Gateway ControlFilter
                preLogger: true
                postLogger: true
        - id: schedule
          uri: http://localhost:8084/
          predicates:
            - Path=/api/schedule/**
          filters:
            - name: ScheduleFilter
              args:
                baseMessage: Spring Cloud Gateway ScheduleFilter
                preLogger: true
                postLogger: true

