spring:
  application:
    name: gateway

---
server:
  port: 8080

---
spring:
  cloud:
    gateway:
      httpclient:
        max-header-size: 32KB
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: operation
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/operation
          filters:
            - RewritePath=/v3/api-docs/operation, /v3/api-docs
            - name: OperationFilter
              args:
                baseMessage: Spring Cloud Gateway OperationFilter
                preLogger: true
                postLogger: true
        - id: control
          uri: http://localhost:8083
          predicates:
            - Path=/v3/api-docs/control
          filters:
            - RewritePath=/v3/api-docs/control, /v3/api-docs
            - name: ControlFilter
              args:
                baseMessage: Spring Cloud Gateway ControlFilter
                preLogger: true
                postLogger: true
        - id: schedule
          uri: http://localhost:8084
          predicates:
            - Path=/v3/api-docs/schedule
          filters:
            - RewritePath=/v3/api-docs/schedule, /v3/api-docs
            - name: ScheduleFilter
              args:
                baseMessage: Spring Cloud Gateway ScheduleFilter
                preLogger: true
                postLogger: true


springdoc:
  swagger-ui:
    urls:
      - name: control
        url: /v3/api-docs/control
      - name: operation
        url: /v3/api-docs/operation
      - name: schedule
        url: /v3/api-docs/schedule
    path: /swagger-ui.html
  api-docs:
    enabled: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG