spring:
  application:
    name: redis-service
  profiles:
    active: prod

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 8  # 최대 활성 커넥션 수
        max-idle: 8     # 최대 유휴 커넥션 수
        min-idle: 0     # 최소 유휴 커넥션 수
      timeout: 3000  # 타임아웃 (밀리초 단위)
    ssl: false  # SSL이 비활성화된 상태

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${HOSTNAME}

logging:
  level:
    root: INFO