spring:
  application:
    name: operation
  profiles:
    active: prod

feature-flags:
  kafka:
    enabled: false  # 카프카 비활성화

server:
  port: 0
  max-http-header-size: 32KB
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.postco.operation
  paths-to-match: /api/**