spring:
  application:
    name: operation

# feature flag 추가
feature-flags:
  kafka:
    enabled: false  # 카프카 비활성화

---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: local

server:
  port: 0
  max-http-header-size: 32KB
  servlet:
    context-path: / 
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Eureka 설정
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.postco.operation
  paths-to-match: /api/**