spring:
  application:
    name: eureka-server
  config:
    activate:
      on-profile: prod

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${HOSTNAME}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/