spring:
  application:
    name: eureka-server
  config:
    activate:
      on-profile: prod

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    preferIpAddress: true
    ip-address: ${EUREKA_HOST}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${server.port}/eureka/