spring:
  application:
    name: eureka-server
  config:
    activate:
      on-profile: prod

server:
  port: ${EUREKA_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${server.port}/eureka/