spring:
  application:
    name: eureka-server
---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:8761/eureka/