# 실제 운영되는 환경입니다.
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  datasource:
    url: jdbc:mysql://postcoil-db.cva0yysaozpe.ap-northeast-2.rds.amazonaws.com:3306/schedule
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: WARN
    com.postco: INFO
