name: CD - Gateway and Eureka

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Gateway artifact
        uses: actions/download-artifact@v4
        with:
          name: gateway-package
          path: .

      - name: Download Eureka artifact
        uses: actions/download-artifact@v4
        with:
          name: eureka-package
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp gateway-package.zip s3://${{ secrets.EB_BUCKET }}/gateway-package.zip
          aws s3 cp eureka-package.zip s3://${{ secrets.EB_BUCKET }}/eureka-package.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name postco-app \
            --version-label gateway-eureka-${GITHUB_SHA::7} \
            --source-bundle S3Bucket="${{ secrets.EB_BUCKET }}",S3Key="gateway-package.zip"
          
          aws elasticbeanstalk update-environment \
            --environment-name gateway-eureka-redis-env \
            --version-label gateway-eureka-${GITHUB_SHA::7}