name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Elastic Beanstalk packages
        uses: actions/download-artifact@v4
        with:
          name: eb-packages
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Gateway to Elastic Beanstalk
        run: |
          aws s3 cp gateway-package.zip s3://${{ secrets.EB_BUCKET }}/gateway-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version \
            --application-name postco-app \
            --version-label gateway-${{ github.sha }} \
            --source-bundle S3Bucket="${{ secrets.EB_BUCKET }}",S3Key="gateway-${{ github.sha }}.zip"
          aws elasticbeanstalk update-environment \
            --environment-name gateway-env \
            --version-label gateway-${{ github.sha }}

#      - name: Deploy Eureka to Elastic Beanstalk
#        run: |
#          aws s3 cp eureka-package.zip s3://${{ secrets.EB_BUCKET }}/eureka-${{ github.sha }}.zip
#          aws elasticbeanstalk create-application-version \
#            --application-name postco-app \
#            --version-label eureka-${{ github.sha }} \
#            --source-bundle S3Bucket="${{ secrets.EB_BUCKET }}",S3Key="eureka-${{ github.sha }}.zip"
#          aws elasticbeanstalk update-environment \
#            --environment-name eureka-redis-env \
#            --version-label eureka-${{ github.sha }}
#
#      - name: Deploy Cache Service to Elastic Beanstalk
#        run: |
#          aws s3 cp cache-service-package.zip s3://${{ secrets.EB_BUCKET }}/cache-service-${{ github.sha }}.zip
#          aws elasticbeanstalk create-application-version \
#            --application-name postco-app \
#            --version-label cache-service-${{ github.sha }} \
#            --source-bundle S3Bucket="${{ secrets.EB_BUCKET }}",S3Key="cache-service-${{ github.sha }}.zip"
#          aws elasticbeanstalk update-environment \
#            --environment-name eureka-redis-env \
#            --version-label cache-service-${{ github.sha }}