name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Elastic Beanstalk package
        uses: actions/download-artifact@v4
        with:
          name: eb-package
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          aws s3 cp eb-package.zip s3://${{ secrets.EB_BUCKET }}/eb-package-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version \
            --application-name postco-app \
            --version-label eb-package-${{ github.sha }} \
            --source-bundle S3Bucket="${{ secrets.EB_BUCKET }}",S3Key="eb-package-${{ github.sha }}.zip"
          aws elasticbeanstalk update-environment \
            --environment-name gateway-eureka-redis-env \
            --version-label eb-package-${{ github.sha }} \
            --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=GATEWAY_PORT,Value=${{ secrets.GATEWAY_PORT }} \
            --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=EUREKA_INSTANCE_HOSTNAME,Value=${{ secrets.EUREKA_INSTANCE_HOSTNAME }} \
            --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=EUREKA_PORT,Value=${{ secrets.EUREKA_PORT }}