name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Set environment variables
        run: |
          echo "EUREKA_HOST=${{ secrets.EUREKA_HOST }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Gateway
        run: |
          cd gateway
          ../gradlew clean build -x test -Dspring.profiles.active=prod --warning-mode all
          mkdir -p ../deployment/gateway
          find build/libs -name '*.jar' -exec cp {} ../deployment/gateway/application.jar \;
          cp -r ../.ebextensions ../deployment/gateway/

      - name: Build Eureka
        run: |
          cd eureka-server
          ../gradlew clean build -x test -Dspring.profiles.active=prod --warning-mode all
          mkdir -p ../deployment/eureka
          find build/libs -name '*.jar' -exec cp {} ../deployment/eureka/application.jar \;
          cp -r ../.ebextensions ../deployment/eureka/

      - name: Prepare deployment packages
        run: |
          cd deployment/gateway && zip -r ../../gateway-package.zip .
          cd ../eureka && zip -r ../../eureka-package.zip .

      - name: Upload Elastic Beanstalk packages
        uses: actions/upload-artifact@v4
        with:
          name: eb-packages
          path: |
            gateway-package.zip
            eureka-package.zip
          retention-days: 1