name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Gateway, Eureka, and Cache Service
        run: |
          ./gradlew :gateway:build :eureka-server:build :cache-service:build -x test -Dspring.profiles.active=prod --warning-mode all
          mkdir -p deployment
          cp gateway/build/libs/*.jar deployment/gateway.jar
          cp eureka-server/build/libs/*.jar deployment/eureka.jar
          cp cache-service/build/libs/*.jar deployment/cache-service.jar
          echo "java -Dserver.port=5000 -jar gateway.jar" > deployment/Procfile
          echo "java -jar eureka.jar &" >> deployment/Procfile
          echo "java -jar cache-service.jar &" >> deployment/Procfile
          mkdir -p deployment/.ebextensions
          cat << EOF > deployment/.ebextensions/01_env.config
          option_settings:
            aws:elasticbeanstalk:application:environment:
              SERVER_PORT: '5000'
              SPRING_PROFILES_ACTIVE: prod
              EUREKA_INSTANCE_HOSTNAME: \${EUREKA_INSTANCE_HOSTNAME}
              EUREKA_PORT: '8761'
              REDIS_HOST: \${REDIS_HOST}
              REDIS_PORT: \${REDIS_PORT}
            aws:elasticbeanstalk:container:java:
              JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
            aws:elasticbeanstalk:container:java:xray:
              XRayEnabled: 'false'
            aws:elasticbeanstalk:environment:proxy:staticfiles:
              /static: static
          
          container_commands:
            01_set_time_zone:
              command: "ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime"
          EOF
          cd deployment && zip -r ../eb-package.zip .

      - name: Upload Elastic Beanstalk package
        uses: actions/upload-artifact@v4
        with:
          name: eb-package
          path: eb-package.zip