name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Gateway
        run: |
          cd gateway
          ../gradlew clean build -x test -Dspring.profiles.active=prod --warning-mode all
          mkdir -p ../deployment/gateway
          find build/libs -name '*.jar' -exec cp {} ../deployment/gateway/application.jar \;

      - name: Build Eureka
        run: |
          cd eureka-server
          ../gradlew clean build -x test -Dspring.profiles.active=prod --warning-mode all
          mkdir -p ../deployment/eureka
          find build/libs -name '*.jar' -exec cp {} ../deployment/eureka/application.jar \;

      - name: Build Cache Service
        run: |
          ./gradlew :cache-service:clean :cache-service:build -x test -Dspring.profiles.active=prod --warning-mode all
          mkdir -p deployment/cache-service
          find cache-service/build/libs -name '*.jar' -exec cp {} deployment/cache-service/application.jar \;

      - name: Prepare deployment package
        run: |
          cp -r .ebextensions deployment/

          # Create start.sh
          cat << 'EOF' > deployment/start.sh
          #!/bin/bash
          java -jar eureka/application.jar &
          java -jar cache-service/application.jar &
          java -Dserver.port=5000 -jar gateway/application.jar
          EOF

          chmod +x deployment/start.sh

          # Create Procfile
          echo "web: bash start.sh" > deployment/Procfile

          cd deployment && zip -r ../eb-package.zip .

      - name: Upload Elastic Beanstalk package
        uses: actions/upload-artifact@v4
        with:
          name: eb-package
          path: eb-package.zip
          retention-days: 1
