name: CI

on:
  push:
    branches:
      - 'feat/cicd/yerimee'
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean and Build without Tests (Prod profile)
        run: ./gradlew clean build -x test -Dspring.profiles.active=prod

      - name: Generate deployment package
        run: |
          mkdir -p deployment
          cp build/libs/*.jar deployment/application.jar
          echo "java -Dspring.profiles.active=prod -jar application.jar" > deployment/Procfile
          cp -r .ebextensions deployment/
          cd deployment && zip -r deployment-package.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment-package
          path: deployment/deployment-package.zip