name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Gateway
        run: |
          cd gateway
          ../gradlew clean build -x test -Dspring.profiles.active=prod
          mkdir -p deployment
          cp build/libs/*.jar deployment/application.jar
          echo "java -Dspring.profiles.active=prod -jar application.jar" > deployment/Procfile
          cp -r ../.ebextensions deployment/
          cd deployment && zip -r gateway-package.zip .

      - name: Build Eureka
        run: |
          cd eureka-server
          ../gradlew clean build -x test -Dspring.profiles.active=prod
          mkdir -p deployment
          cp build/libs/*.jar deployment/application.jar
          echo "java -Dspring.profiles.active=prod -jar application.jar" > deployment/Procfile
          cp -r ../.ebextensions deployment/
          cd deployment && zip -r eureka-package.zip .

      - name: Build Cache Service
        run: |
          cd cache-service
          ../gradlew clean build -x test -Dspring.profiles.active=prod
          mkdir -p deployment
          cp build/libs/*.jar deployment/application.jar
          echo "java -Dspring.profiles.active=prod -jar application.jar" > deployment/Procfile
          cp -r ../.ebextensions deployment/
          cd deployment && zip -r cache-service-package.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-packages
          path: |
            gateway/deployment/gateway-package.zip
            eureka-server/deployment/eureka-package.zip
            cache-service/deployment/cache-service-package.zip
          retention-days: 1